version: '3.3'

services:
#####node 1 - master ####
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    ports:
      - "9200:9200"
      - "9300:9300"
    #configs:
    #  - source: elastic_config
    #    target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      node.name: elasticsearch
      #node.master: "true"
      #node.data: "false"
      #node.ingest: "false"
      cluster.name: docker-cluster
      #discovery.zen.ping.unicast.hosts: elasticsearch,elasticsearch2
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      discovery.zen.minimum_master_nodes: 2
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /data/elk:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime
########## node 2 ########      
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    #configs:
    #  - source: elastic_config
    #    target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      cluster.name: docker-cluster
      node.name: elasticsearch2
      discovery.zen.ping.unicast.hosts: elasticsearch
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /data/elk2:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime
######################################### Elasticsearch fim ##################    
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.0
    ports:
      - "5044:5044"
      - "5000:5000"
      - "5000:5000/udp"
      - "9600:9600"
    configs:
      #ogirinal
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
      #- source: logstash_winad
      #  target: /usr/share/logstash/pipeline/winad.conf
      ###fim original
      #- source: 01-input.conf
      #  target: /etc/logstash/conf.d/01-input.conf
      #- source: 11-pfsense.conf
      #  target: /etc/logstash/conf.d/11-pfsense.conf
      #- source: 10-syslog.conf
      #  target: /etc/logstash/conf.d/10.syslog.conf
      #- source: 30-outputs.conf
      #  target: /etc/logstash/conf.d/30-outputs.conf
      - source: pfsense.grok
        target: /etc/logstash/conf.d/patterns/pfsense.grok
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk
    volumes:
      - /etc/localtime:/etc/localtime
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

configs:
##elasticsearsh configs
  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
#Logstash configs
  logstash_config:
    file: ./logstash/config/logstash.yml
  #01-input.conf:
  #  file: ./logstash/config/01-inputs.conf
  #10-syslog.conf:
  #  file: ./logstash/config/10-syslog.conf
  #11-pfsense.conf:
  #  file: ./logstash/config/11-pfsense.conf
  #30-outputs.conf:
  #  file: ./logstash/config/30-outputs.conf
  pfsense.grok:
    file: ./logstash/pipeline/pfsense.grok
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf
  #logstash_winad:
  #  file: ./logstash/pipeline/winad.conf
#kibana config
  kibana_config:
    file: ./kibana/config/kibana.yml
    

networks:
  elk:
    driver: overlay
